site_name: "Fast API Application Template + Cloud Run Deployment Template"
site_description: "This is simple FastAPI application created using Uvicorn framework. It will also deploy the FastAPI demo application to the Cloud Run environment."

nav:
  - Introduction: index.md